{
    "openapi": "3.0.1",
    "info": {
        "title": "Lists",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "STARTER",
            "cms": "STARTER"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "You want to bulk add contacts to a particular list, or remove company records from a company list.",
        "x-hubspot-related-documentation": [
            {
                "name": "Lists Guide",
                "url": "https://developers.hubspot.com/beta-docs/guides/api/crm/lists/overview"
            }
        ],
        "x-hubspot-introduction": "Use the lists API to manage list memberships for object lists."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com/crm/v3/lists"
        }
    ],
    "tags": [
        {
            "name": "Lists"
        },
        {
            "name": "Memberships"
        },
        {
            "name": "Folders"
        },
        {
            "name": "Mapping"
        }
    ],
    "paths": {
        "/{listId}/update-list-name": {
            "put": {
                "tags": [
                    "Lists"
                ],
                "summary": "Update List Name",
                "description": "Update the name of a list. The name must be globally unique relative to all other public lists in the portal.",
                "operationId": "put-/{listId}/update-list-name_updateName",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/memberships/add-and-remove": {
            "put": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Add and/or Remove Records from a List",
                "description": "Add and\/or remove records that have already been created in the system to and\/or from a list.\n\nThis endpoint only works for lists that have a _processingType_ of _MANUAL_ or _SNAPSHOT_.",
                "operationId": "put-/{listId}/memberships/add-and-remove_addAndRemove",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "Fetch List by ID",
                "description": "Fetch a single list by **ILS list ID**.",
                "operationId": "get-/{listId}_getById",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Lists"
                ],
                "summary": "Delete a List",
                "description": "Delete a list by **ILS list ID**. Lists deleted through this endpoint can be restored up to 90-days following the delete. After 90-days, the list is purged and can no longer be restored.",
                "operationId": "delete-/{listId}_remove",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/update-list-filters": {
            "put": {
                "tags": [
                    "Lists"
                ],
                "summary": "Update List Filter Definition",
                "description": "Update the filter branch definition of a _DYNAMIC_ list. Once updated, the list memberships will be re-evaluated and updated to match the new definition.",
                "operationId": "put-/{listId}/update-list-filters_updateListFilters",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/search": {
            "post": {
                "tags": [
                    "Lists"
                ],
                "summary": "Search Lists",
                "description": "Search lists by list name or page through all lists by providing an empty _query_ value.",
                "operationId": "post-/search_doSearch",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/folders/move-list": {
            "put": {
                "tags": [
                    "Folders"
                ],
                "summary": "Moves a list to a given folder",
                "description": "Given a list and a folder, the list will be moved to that folder.",
                "operationId": "put-/folders/move-list_moveList",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/memberships/add": {
            "put": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Add Records to a List",
                "description": "Add the records provided to the list. Records that do not exist or that are already members of the list are ignored.\n\nThis endpoint only works for lists that have a _processingType_ of _MANUAL_ or _SNAPSHOT_.",
                "operationId": "put-/{listId}/memberships/add_add",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/object-type-id/{objectTypeId}/name/{listName}": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "Fetch List by Name",
                "description": "Fetch a single list by list name and object type.",
                "operationId": "get-/object-type-id/{objectTypeId}/name/{listName}_getByName",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/folders/{folderId}/move/{newParentFolderId}": {
            "put": {
                "tags": [
                    "Folders"
                ],
                "summary": "Moves a folder",
                "description": "This moves the folder from its current location to a new location. It updates the parent of this folder to the new Id given.",
                "operationId": "put-/folders/{folderId}/move/{newParentFolderId}_move",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/idmapping": {
            "get": {
                "tags": [
                    "Mapping"
                ],
                "summary": "Translate legacy list ID to modern ID",
                "description": "This API allows translation of legacy list id to list id. This is a temporary API allowed for mapping old id's to new id's and will expire on May 30th, 2025.",
                "operationId": "get-/idmapping_translateLegacyListIdToListId",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Mapping"
                ],
                "summary": "Batch translate legacy list IDs",
                "description": "This API allows translation of a batch of legacy list id's to list id's. This allows for a maximum of 10,000 id's. This is a temporary API allowed for mapping old id's to new id's and will expire on May 30th, 2025.",
                "operationId": "post-/idmapping_translateLegacyListIdToListIdBatch",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/restore": {
            "put": {
                "tags": [
                    "Lists"
                ],
                "summary": "Restore a List",
                "description": "Restore a previously deleted list by **ILS list ID**. Deleted lists are eligible to be restored up-to 90-days after the list has been deleted.",
                "operationId": "put-/{listId}/restore_restore",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/folders/{folderId}/rename": {
            "put": {
                "tags": [
                    "Folders"
                ],
                "summary": "Rename a folder",
                "description": "Renames the given folderId with a new name.",
                "operationId": "put-/folders/{folderId}/rename_rename",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/memberships/join-order": {
            "get": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Get memberships by join date",
                "description": "Fetch the memberships of a list in order sorted by the time the records were added to the list.\n\nThe _recordId_s are sorted in *ascending* order if an _after_ offset or no offset is provided. If only a _before_ offset is provided, then the records are sorted in *descending* order.\n\nThe _after_ offset parameter will take precedence over the _before_ offset in a case where both are provided.",
                "operationId": "get-/{listId}/memberships/join-order_getPageOrderedByAddedToListDate",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/memberships/add-from/{sourceListId}": {
            "put": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Add all records from source list",
                "description": "Add all of the records from a *source list* (specified by the _sourceListId_) to a *destination list* (specified by the _listId_). Records that are already members of the *destination list* will be ignored. The *destination* and *source list* IDs must be different. The *destination* and *source lists* must contain records of the same type (e.g. contacts, companies, etc.).\n\nThis endpoint only works for *destination lists* that have a _processingType_ of _MANUAL_ [...]",
                "operationId": "put-/{listId}/memberships/add-from/{sourceListId}_addAllFromList",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/records/{objectTypeId}/{recordId}/memberships": {
            "get": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Get lists record is member of",
                "description": "For given record provide lists this record is member of.",
                "operationId": "get-/records/{objectTypeId}/{recordId}/memberships_getLists",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/": {
            "get": {
                "tags": [
                    "Lists"
                ],
                "summary": "Fetch Multiple Lists",
                "description": "Fetch multiple lists in a single request by **ILS list ID**. The response will include the definitions of all lists that exist for the _listIds_ provided.",
                "operationId": "get-/_getAll",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Lists"
                ],
                "summary": "Create List",
                "description": "Create a new list with the provided object list definition.",
                "operationId": "post-/_create",
                "security": [
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write"
                        ]
                    }
                ]
            }
        },
        "/folders": {
            "get": {
                "tags": [
                    "Folders"
                ],
                "summary": "Retrieves a folder.",
                "description": "Retrieves a folder and recursively includes all folders via the childNodes attribute.  The child lists field will be empty in all child nodes. Only the folder retrieved will include the child lists in that folder.",
                "operationId": "get-/folders_getAll",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Folders"
                ],
                "summary": "Creates a folder",
                "description": "Creates a folder with the given information.",
                "operationId": "post-/folders_create",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/folders/{folderId}": {
            "delete": {
                "tags": [
                    "Folders"
                ],
                "summary": "Deletes a folder",
                "description": "Deletes the folder with the given Id.",
                "operationId": "delete-/folders/{folderId}_remove",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/memberships": {
            "get": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Fetch List Memberships Ordered by ID",
                "description": "Fetch the memberships of a list in order sorted by the _recordId_ of the records in the list.\n\nThe _recordId_s are sorted in *ascending* order if an _after_ offset or no offset is provided. If only a _before_ offset is provided, then the records are sorted in *descending* order.\n\nThe _after_ offset parameter will take precedence over the _before_ offset in a case where both are provided.",
                "operationId": "get-/{listId}/memberships_getPage",
                "security": [
                    {
                        "private_apps": [
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.read"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Delete All Records from a List",
                "description": "Remove **all** of the records from a list. ***Note:*** *The list is not deleted.*\n\nThis endpoint only works for lists that have a _processingType_ of _MANUAL_ or _SNAPSHOT_.\n\nThis endpoint only supports lists that have less than 100,000 memberships.",
                "operationId": "delete-/{listId}/memberships_removeAll",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        },
        "/{listId}/memberships/remove": {
            "put": {
                "tags": [
                    "Memberships"
                ],
                "summary": "Remove Records from a List",
                "description": "Remove the records provided from the list. Records that do not exist or that are not members of the list are ignored.\n\nThis endpoint only works for lists that have a _processingType_ of _MANUAL_ or _SNAPSHOT_.",
                "operationId": "put-/{listId}/memberships/remove_remove",
                "security": [
                    {
                        "oauth2": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "oauth2": [
                            "crm.lists.write",
                            "crm.lists.read"
                        ]
                    },
                    {
                        "private_apps": [
                            "cms.membership.access_groups.write",
                            "crm.lists.read"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.lists.read": " ",
                            "cms.membership.access_groups.write": "Write membership access groups.",
                            "crm.lists.write": " "
                        }
                    }
                }
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header",
                "x-ballerina-name": "privateApp"
            }
        }
    },
    "x-hubspot-available-client-libraries": [
        "PHP",
        "Node",
        "Ruby",
        "Python"
    ],
    "x-hubspot-product-tier-requirements": {
        "marketing": "STARTER",
        "cms": "STARTER"
    },
    "x-hubspot-documentation-banner": "NONE"
}